// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { HealthData, HealthResponses, ListTitlesData, ListTitlesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health
 *
 * Cheapest possible proof the API is up and reachable.
 *
 * `scripts/setup` and the clean-runner CI job both poll this, so the scaffold
 * is verifiable before any feature endpoint exists. It also gives the phone a
 * way to distinguish "cannot reach the server" from "server is up but has no
 * titles" — the two states FR-008 requires be told apart.
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>) => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * List every title
 *
 * Every title in the catalog.
 *
 * No pagination or filtering — vertical 003 concerns.
 *
 * Rows do arrive ordered, because `core.models.Title.Meta.ordering` is set for
 * the admin's benefit, so the SQL carries `ORDER BY created_at DESC`. The
 * contract still promises nothing about order, and that is deliberate: a
 * client must not come to depend on an ordering that exists as a side effect
 * of an admin convenience. T018 tests the contract's silence, not this
 * default.
 *
 * An empty catalog returns `[]` with 200, never 404. That is what makes FR-008
 * satisfiable: "no titles" has to be a *success* so a client can distinguish
 * it from "could not reach the server". A 404 would collapse both into one
 * failure path, and the two need different messages because they need
 * different reactions from the person reading them.
 */
export const listTitles = <ThrowOnError extends boolean = false>(options?: Options<ListTitlesData, ThrowOnError>) => (options?.client ?? client).get<ListTitlesResponses, unknown, ThrowOnError>({ url: '/api/titles', ...options });
