// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * TitleOut
 *
 * One title, as clients see it.
 *
 * `created_at` is deliberately absent. It exists on the model for provenance,
 * and no client needs it — a field in the contract is
 * a field two clients can come to depend on, and removing it later is a
 * breaking change made for no reason.
 */
export type TitleOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ListTitlesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/titles';
};

export type ListTitlesResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<TitleOut>;
};

export type ListTitlesResponse = ListTitlesResponses[keyof ListTitlesResponses];
